//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1128 with alias "hasBusinessHours"
	/// <summary>_HasBusinessHours</summary>
	public partial interface IHasBusinessHours : IPublishedContent
	{
		/// <summary>openingHours</summary>
		IEnumerable<MBran.Timings.Models.ValueType.Timing> OpeningHours { get; }
	}

	/// <summary>_HasBusinessHours</summary>
	[PublishedContentModel("hasBusinessHours")]
	public partial class HasBusinessHours : PublishedContentModel, IHasBusinessHours
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hasBusinessHours";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HasBusinessHours(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HasBusinessHours, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// openingHours
		///</summary>
		[ImplementPropertyType("openingHours")]
		public IEnumerable<MBran.Timings.Models.ValueType.Timing> OpeningHours
		{
			get { return GetOpeningHours(this); }
		}

		/// <summary>Static getter for openingHours</summary>
		public static IEnumerable<MBran.Timings.Models.ValueType.Timing> GetOpeningHours(IHasBusinessHours that) { return that.GetPropertyValue<IEnumerable<MBran.Timings.Models.ValueType.Timing>>("openingHours"); }
	}
}
